version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: hyper
    versions:
    - 0.14.2
    - 0.14.4
    - 0.14.5
    - 0.14.6
  - dependency-name: serde
    versions:
    - 1.0.123
    - 1.0.124
  - dependency-name: serde_derive
    versions:
    - 1.0.123
    - 1.0.124
  - dependency-name: juniper_hyper
    versions:
    - 0.6.3
  - dependency-name: juniper
    versions:
    - 0.15.3
  - dependency-name: diesel
    versions:
    - 1.4.5
